# JVM args for Gradle daemon
org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:+UseParallelGC
# Parallel + caching for the multi-module build
org.gradle.parallel=true
org.gradle.caching=true

# Kotlin
kotlin.code.style=official

# AndroidX
android.useAndroidX=true
# Per-module R classes (faster, smaller)
android.nonTransitiveRClass=true
